# Generated by Django 4.0.5 on 2022-08-06 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0003_pet_avatar_pet_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.animal'),
        ),
    ]
