# Generated by Django 4.1 on 2022-10-22 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0003_adoptrequest_adopt_reason_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adoptrequest',
            old_name='adopt',
            new_name='adopter',
        ),
    ]
